from pydantic import BaseModel, Field


class RagResponse(BaseModel):
    result: str = Field(description="The main answer generated by the agent.")
    sources: list[str] = Field(
        description="List of source URLs referenced in the answer."
    )
    detected_city: str | None = Field(
        default=None,
        description="The name of the city discussed (e.g. 'Paris'). Use this if a city is mentioned in the query OR the response.",
    )
